---
title: Venn Diagram
author: Joey Yang
date: '2021-09-22'
slug: venn-diagram
categories:
  - R
tags:
  - plot
output:
  prettydoc::html_pretty:
  #  theme: lumen
  #rmarkdown::html_document:
  theme: architect
---

Venn Diagram can be created by various Packages:
ggven, ggVennDiagram, RAM, and VennDiagram

## Generate Data

```{r data}
# Generate 3 sets of 200 words
set1 <- paste(rep("word_" , 200) , sample(c(1:1000) , 200 , replace=F) , sep="")
set2 <- paste(rep("word_" , 200) , sample(c(1:1000) , 200 , replace=F) , sep="")
set3 <- paste(rep("word_" , 200) , sample(c(1:1000) , 200 , replace=F) , sep="")

# List of items
x <- list(A=set1, B=set2)

# List of items
y <- list(A=set1, B=set2, C=set3)
names(y)
```
## Create Venn diagrams using the ggven R package

### 2D Venn diagram

```{r message=FALSE}
library("ggvenn")

ggvenn(y, columns = c("A", "B"),stroke_size = 0.5)
```

### 3D Venn diagram

```{r,echo=FALSE}
# plot
ggvenn(y, stroke_size = 0.5)

```
